// Regenerates the conformance fixtures under `fixtures/`.
//
// The fixtures are the portable definition of the on-disk format (see
// `docs/format/workspace-v1.md`), so they are generated by the real domain
// types rather than written by hand — a hand-transcribed corpus documents what
// someone believed the code does, which is exactly the thing a rewrite must not
// trust.
//
//   dart run tool/generate_fixtures.dart
//
// Identifiers and timestamps are hardcoded so output is byte-stable across
// runs. `test/format/fixture_conformance_test.dart` then holds it still.
library;

import 'dart:convert';
import 'dart:io';

import 'package:might_do/domain/calendar_date.dart';
import 'package:might_do/domain/rank.dart';
import 'package:might_do/domain/status.dart';
import 'package:might_do/domain/task.dart';
import 'package:might_do/domain/workspace_config.dart';
import 'package:might_do/storage/workspace.dart';
import 'package:path/path.dart' as p;

/// Fixed ULIDs. Real ones are random; these are legible so a failing assertion
/// names something a human can find. All are valid lowercase Crockford base32.
const _prefix = '01m07z000000000000000000';

String _id(String suffix) {
  final value = '$_prefix$suffix';
  if (value.length != 26) {
    throw StateError('id "$value" is ${value.length} chars, expected 26');
  }
  return value;
}

final statusBacklog = _id('s1');
final statusNotStarted = _id('s2');
final statusInProgress = _id('s3');
final statusBlocked = _id('s4');
final statusDone = _id('s5');
final statusAbandoned = _id('s6');

final categoryWork = _id('c1');
final categoryHome = _id('c2');

final taskMaximal = _id('t1');
final taskMinimal = _id('t2');
final taskText = _id('t3');
final taskCompleted = _id('t4');
final taskRanked = _id('t5');
final taskTrashed = _id('t6');

Future<void> main() async {
  final root = Directory('fixtures');
  if (await root.exists()) await root.delete(recursive: true);

  await _writeWorkspace(Directory(p.join(root.path, 'workspace-v1')));
  await _writeTolerance(Directory(p.join(root.path, 'tolerance')));
  await _writeVectors(Directory(p.join(root.path, 'vectors')));

  stdout.writeln('Fixtures written to ${root.path}/');
}

// ---------------------------------------------------------------------------
// The canonical workspace: what the app writes, byte for byte.
// ---------------------------------------------------------------------------

Future<void> _writeWorkspace(Directory dir) async {
  final workspace = Workspace(dir);
  await workspace.ensureLayout();

  await workspace.trashTasksDir.create(recursive: true);
  await workspace.trashAttachmentsDir.create(recursive: true);

  final config = WorkspaceConfig(
    defaultStatusId: statusNotStarted,
    statuses: [
      Status(
        id: statusBacklog,
        name: 'Backlog',
        type: StatusType.initial,
        order: 0,
        hiddenFromBoard: true,
      ),
      Status(
        id: statusNotStarted,
        name: 'Not Started',
        type: StatusType.initial,
        order: 1,
      ),
      Status(
        id: statusInProgress,
        name: 'In Progress',
        type: StatusType.active,
        order: 2,
      ),
      Status(
        id: statusBlocked,
        name: 'Blocked',
        type: StatusType.active,
        order: 3,
      ),
      Status(
        id: statusDone,
        name: 'Done',
        type: StatusType.finalType,
        order: 4,
      ),
      Status(
        id: statusAbandoned,
        name: 'Abandoned',
        type: StatusType.finalType,
        order: 5,
        hiddenFromBoard: true,
      ),
    ],
    categories: [
      // Colours are ARGB ints. 0xFF2E7D32 exceeds a signed 32-bit int, which is
      // the trap for any port that types this field as `int`/`Int32`.
      const Category(id: categoryWorkRef, name: 'Work', color: 0xFF2E7D32),
      const Category(id: categoryHomeRef, name: 'Home & Garden', color: 0x80D32F2F),
    ],
    tags: [
      for (var i = 1; i <= 10; i++)
        Tag(id: _tagId(i), name: i == 3 ? 'needs review' : 'tag-$i'),
    ],
  );
  await writeJsonAtomic(workspace.configFile, config.toJson());

  for (final task in _tasks()) {
    await writeJsonAtomic(workspace.taskFile(task.id), task.toJson());
  }

  // A trashed task lives under .trash/tasks/ in exactly the same shape.
  await writeJsonAtomic(
    File(p.join(workspace.trashTasksDir.path, '$taskTrashed.json')),
    _trashedTask().toJson(),
  );

  // The attachment's bytes. The JSON only names it; the file is what makes the
  // copy authoritative.
  await File(p.join(workspace.attachmentsDir.path, _attachmentStoredName))
      .writeAsString('might-do fixture attachment\n');

  // Files in tasks/ that the app did not write. Every one of these must be
  // reported as a conflict, never loaded and never silently skipped.
  for (final name in expectedConflicts.keys) {
    await File(p.join(workspace.tasksDir.path, name))
        .writeAsString('{"note": "conflict artefact, not a task file"}\n');
  }
}

/// Files planted in `tasks/` that the app did not write, and the task id
/// recoverable from each. Null means no ULID is embedded in the name.
final Map<String, String?> expectedConflicts = {
  '$taskMaximal-LAPTOP.json': taskMaximal, // OneDrive
  '$taskMinimal (conflicted copy 2026-08-16).json': taskMinimal, // Dropbox
  '$taskText 2.json': taskText, // iCloud Drive
  'scratch-notes.json': null, // no recoverable task id
};

const categoryWorkRef = '01m07z000000000000000000c1';
const categoryHomeRef = '01m07z000000000000000000c2';

String _tagId(int i) => _id('g${i == 10 ? 'a' : i}');

const _attachmentStoredName =
    '01m07z000000000000000000a1-quarterly-plan.pdf';

List<Task> _tasks() => [
      _maximalTask(),
      _minimalTask(),
      _textEdgeTask(),
      _completedTask(),
      _rankedTask(),
    ];

/// Every optional field populated, every collection non-empty.
Task _maximalTask() => Task(
      id: taskMaximal,
      summary: 'Draft the quarterly plan',
      description:
          'Pull last quarter\'s numbers together and write the narrative '
          'before the board meeting.',
      statusId: statusInProgress,
      categoryId: categoryWork,
      tagIds: [for (var i = 1; i <= 10; i++) _tagId(i)],
      priority: Priority.critical,
      dueDate: const CalendarDate(2026, 8, 21),
      completedAt: null,
      estimateMinutes: 240,
      totalTimeMinutes: 315,
      boardRank: 'h',
      steps: [
        Step(id: _id('p1'), text: 'Export the figures', done: true),
        Step(id: _id('p2'), text: 'Write the narrative'),
        Step(id: _id('p3'), text: 'Circulate for comment', done: true),
      ],
      notes: [
        Note(
          id: _id('n1'),
          createdAt: DateTime.utc(2026, 8, 14, 9, 5, 30, 123),
          body: 'Figures are out of date; chased finance.',
        ),
        Note(
          // Microsecond precision: DateTime.now() produces six fractional
          // digits on desktop, so the format must carry them.
          id: _id('n2'),
          createdAt: DateTime.utc(2026, 8, 15, 16, 42, 7, 890, 123),
          body: 'Finance came back.\n\nNumbers now agreed with Priya.',
        ),
      ],
      attachments: [
        Attachment(
          id: _id('a1'),
          originalName: 'quarterly plan.pdf',
          storedName: _attachmentStoredName,
          sizeBytes: 184320,
          addedAt: DateTime.utc(2026, 8, 14, 9, 6),
        ),
      ],
      reminders: [
        // Pending: neither fired nor dismissed.
        Reminder(id: _id('r1'), remindAt: DateTime.utc(2026, 8, 20, 8, 0)),
        // Fired but not acknowledged: still outstanding.
        Reminder(
          id: _id('r2'),
          remindAt: DateTime.utc(2026, 8, 18, 8, 0),
          firedAt: DateTime.utc(2026, 8, 18, 8, 0, 1, 5),
        ),
        // Dismissed: no longer outstanding.
        Reminder(
          id: _id('r3'),
          remindAt: DateTime.utc(2026, 8, 16, 8, 0),
          firedAt: DateTime.utc(2026, 8, 16, 8, 0, 0, 500),
          dismissedAt: DateTime.utc(2026, 8, 16, 9, 15, 22),
        ),
      ],
      createdAt: DateTime.utc(2026, 8, 14, 9, 0, 0),
      updatedAt: DateTime.utc(2026, 8, 16, 9, 15, 22, 4, 60),
    );

/// Nothing optional set. Every nullable field is written as an explicit null
/// and every list as `[]` — absent keys are read, but never written.
Task _minimalTask() => Task(
      id: taskMinimal,
      summary: 'Buy milk',
      statusId: statusNotStarted,
      boardRank: 'i',
      createdAt: DateTime.utc(2026, 8, 15, 7, 30),
      updatedAt: DateTime.utc(2026, 8, 15, 7, 30),
    );

/// The escaping canary. If a port's JSON writer escapes non-ASCII or
/// HTML-sensitive characters, this is the file that catches it.
Task _textEdgeTask() => Task(
      id: taskText,
      summary: 'Café — 日本語 🎉 "quoted" & <tagged>',
      description: 'Backslash \\ slash / tab\there\n'
          'Newline above. Apostrophe’s and an ampersand & a <b>tag</b>.\n'
          'Control char:  end.',
      statusId: statusBacklog,
      categoryId: categoryHome,
      tagIds: [_tagId(3)],
      priority: Priority.low,
      boardRank: 'g',
      notes: [
        Note(
          id: _id('n3'),
          createdAt: DateTime.utc(2026, 8, 15, 12, 0),
          body: 'Emoji in a note: 🎉🎉 and a lone quote: "',
        ),
      ],
      createdAt: DateTime.utc(2026, 8, 15, 11, 0),
      updatedAt: DateTime.utc(2026, 8, 15, 12, 0),
    );

/// In a status of type Final, so completedAt is stamped.
Task _completedTask() => Task(
      id: taskCompleted,
      summary: 'Renew the domain',
      description: 'Expires in September.',
      statusId: statusDone,
      categoryId: categoryWork,
      priority: Priority.high,
      dueDate: const CalendarDate(2026, 9, 1),
      completedAt: DateTime.utc(2026, 8, 16, 14, 22, 9, 777),
      estimateMinutes: 15,
      totalTimeMinutes: 10,
      boardRank: 'j',
      createdAt: DateTime.utc(2026, 8, 10, 10, 0),
      updatedAt: DateTime.utc(2026, 8, 16, 14, 22, 9, 777),
    );

/// Deep fractional rank, to catch a port that treats boardRank as a number.
Task _rankedTask() => Task(
      id: taskRanked,
      summary: 'Reordered by hand',
      statusId: statusInProgress,
      priority: Priority.medium,
      boardRank: 'hzzzzy',
      createdAt: DateTime.utc(2026, 8, 16, 8, 0),
      updatedAt: DateTime.utc(2026, 8, 16, 8, 0),
    );

Task _trashedTask() => Task(
      id: taskTrashed,
      summary: 'Abandoned experiment',
      description: 'Kept because nothing purges the trash automatically.',
      statusId: statusAbandoned,
      priority: Priority.low,
      completedAt: DateTime.utc(2026, 8, 12, 17, 0),
      boardRank: 'k',
      createdAt: DateTime.utc(2026, 8, 11, 9, 0),
      updatedAt: DateTime.utc(2026, 8, 12, 17, 0),
    );

// ---------------------------------------------------------------------------
// Tolerance: input the reader must accept, and the canonical form it becomes.
// ---------------------------------------------------------------------------

Future<void> _writeTolerance(Directory dir) async {
  final inputs = Directory(p.join(dir.path, 'input'));
  final expected = Directory(p.join(dir.path, 'expected'));
  await inputs.create(recursive: true);
  await expected.create(recursive: true);

  // Every optional key absent rather than null, and lists missing entirely.
  const sparse = {
    'schemaVersion': 1,
    'id': '01m07z000000000000000000t7',
    'summary': 'Only the required keys',
    'statusId': '01m07z000000000000000000s2',
    'createdAt': '2026-08-15T07:30:00.000Z',
    'updatedAt': '2026-08-15T07:30:00.000Z',
  };

  // Timestamps that are valid ISO-8601 but not the form we write: a zone
  // offset instead of Z, and no fractional part.
  const offsets = {
    'schemaVersion': 1,
    'id': '01m07z000000000000000000t8',
    'summary': 'Non-UTC timestamps',
    'statusId': '01m07z000000000000000000s2',
    'priority': 'high',
    'dueDate': '2026-08-21',
    'completedAt': '2026-08-16T16:22:09+02:00',
    'boardRank': 'm',
    'notes': [
      {
        'id': '01m07z000000000000000000n4',
        'createdAt': '2026-08-15T12:00:00Z',
        'body': 'No fractional seconds on the way in.',
      },
    ],
    'createdAt': '2026-08-10T10:00:00.5Z',
    'updatedAt': '2026-08-16T14:22:09.7654321Z',
  };

  // Unknown keys from a future schema version. Dropped on read, so a
  // round-trip through an older build silently discards them — a real risk of
  // the format, recorded here so the port behaves identically rather than
  // differently.
  const future = {
    'schemaVersion': 1,
    'id': '01m07z000000000000000000t9',
    'summary': 'Carries keys this version does not know',
    'statusId': '01m07z000000000000000000s2',
    'boardRank': 'n',
    'colour': 'purple',
    'recurrence': {'every': 'week'},
    'createdAt': '2026-08-15T07:30:00.000Z',
    'updatedAt': '2026-08-15T07:30:00.000Z',
  };

  const cases = {
    'sparse': sparse,
    'offset-timestamps': offsets,
    'future-keys': future,
  };

  const encoder = JsonEncoder.withIndent('  ');
  for (final entry in cases.entries) {
    await File(p.join(inputs.path, '${entry.key}.json'))
        .writeAsString('${encoder.convert(entry.value)}\n');
    await writeJsonAtomic(
      File(p.join(expected.path, '${entry.key}.json')),
      Task.fromJson(Map<String, dynamic>.from(entry.value)).toJson(),
    );
  }

  // A config whose statuses are stored out of order: reading sorts by `order`,
  // and writing emits them sorted, so this normalises.
  final unsorted = {
    'schemaVersion': 1,
    'defaultStatusId': statusNotStarted,
    'statuses': [
      {
        'id': statusDone,
        'name': 'Done',
        'type': 'final',
        'order': 2,
        'hiddenFromBoard': false,
      },
      {'id': statusNotStarted, 'name': 'Not Started', 'type': 'initial', 'order': 0},
      {
        'id': statusInProgress,
        'name': 'In Progress',
        'type': 'active',
        'order': 1,
      },
    ],
  };
  await File(p.join(inputs.path, 'config-unsorted.json'))
      .writeAsString('${encoder.convert(unsorted)}\n');
  await writeJsonAtomic(
    File(p.join(expected.path, 'config-unsorted.json')),
    WorkspaceConfig.fromJson(Map<String, dynamic>.from(unsorted)).toJson(),
  );
}

// ---------------------------------------------------------------------------
// Vectors for the pure functions a port has to reimplement.
// ---------------------------------------------------------------------------

Future<void> _writeVectors(Directory dir) async {
  await dir.create(recursive: true);

  const rankPairs = [
    ['', ''],
    ['', 'i'],
    ['i', ''],
    ['h', 'i'],
    ['a', 'b'],
    ['hzzzzy', 'i'],
    ['h', 'h1'],
    ['1', '2'],
    ['zz', 'zzz'],
  ];
  await _writeVector(dir, 'ranks.json', {
    'comment': 'rankBetween(before, after). Empty string means unbounded on '
        'that side. Result must sort strictly between the two under ordinary '
        'ordinal string comparison, and must never end in "0".',
    'between': [
      for (final pair in rankPairs)
        {
          'before': pair[0],
          'after': pair[1],
          'result': rankBetween(pair[0], pair[1]),
        },
    ],
    'initialRanks': {'count': 5, 'result': initialRanks(5)},
    'rejected': [
      {'before': 'i', 'after': 'h', 'why': 'before must sort before after'},
      {'before': 'i', 'after': 'i', 'why': 'bounds must differ'},
      {'before': 'a0', 'after': '', 'why': 'rank must not end in 0'},
      {'before': 'A', 'after': '', 'why': 'base-36 is lowercase'},
    ],
  });

  const dateInputs = [
    '2026-08-21',
    '2026-02-29',
    '2024-02-29',
    '2026-02-30',
    '2026-13-01',
    '2026-00-10',
    '2026-08-00',
    '2026-8-21',
    '26-08-21',
    '2026-08-21T00:00:00Z',
    '',
  ];
  await _writeVector(dir, 'calendar-dates.json', {
    'comment': 'CalendarDate.tryParse. A due date is a day: strictly '
        'yyyy-MM-dd, no time, no zone, and non-existent days are rejected.',
    'cases': [
      for (final input in dateInputs)
        {'input': input, 'parsed': CalendarDate.tryParse(input)?.toIso()},
    ],
  });

  const fileNames = [
    '01m07z000000000000000000t1.json',
    '01M07Z000000000000000000T1.json',
    '01m07z000000000000000000t1-LAPTOP.json',
    '01m07z000000000000000000t1 (conflicted copy 2026-08-16).json',
    '01m07z000000000000000000t1 2.json',
    '01m07z000000000000000000t1.json.tmp',
    '01m07z000000000000000000t.json',
    '01m07z0000000000000000000t1.json',
    '01i07z000000000000000000t1.json',
    'scratch-notes.json',
    'config.json',
  ];
  await _writeVector(dir, 'conflicts.json', {
    'comment': 'Files planted in fixtures/workspace-v1/tasks/ that a load must '
        'surface as conflict artefacts rather than tasks. Sorted newest '
        'modified first at runtime, which mtime decides, so order is not '
        'fixed here.',
    'files': [
      for (final entry in expectedConflicts.entries)
        {'fileName': entry.key, 'taskId': entry.value},
    ],
  });

  await _writeVector(dir, 'filenames.json', {
    'comment': 'isOwnTaskFile: a 26-char Crockford base32 ULID plus ".json", '
        'matched case-insensitively. Anything else in tasks/ is a conflict '
        'artefact, except our own in-flight ".tmp" writes, which are skipped.',
    'cases': [
      for (final name in fileNames)
        {
          'fileName': name,
          'isOwnTaskFile': isOwnTaskFile(name),
          'isConflictArtefact':
              !isOwnTaskFile(name) && !name.endsWith('.tmp'),
        },
    ],
  });
}

Future<void> _writeVector(
  Directory dir,
  String name,
  Map<String, dynamic> body,
) =>
    writeJsonAtomic(File(p.join(dir.path, name)), body);
